services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: discodeit
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d discodeit" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      STORAGE_LOCAL_ROOT_PATH: ${STORAGE_LOCAL_ROOT_PATH:-.discodeit/storage}
      DB_URL: jdbc:postgresql://db:5432/discodeit
    volumes:
      - discodeit-storage:/app/.discodeit
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
  discodeit-storage: