server:
  port: ${PORT:8080}

spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}

logging:
  level:
    com.sprint.mission.discodeit: INFO
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF