spring:
  application:
    name: discodeit

server:
  port: 8080
# default이지만 8081로 바꿀때 참고하라고.

discodeit:
  repository:
    type: jcf
    file-directory: .discodeit

    springdoc:
      swagger-ui:
        path: /swagger-ui.html       # Swagger UI 접속 경로
      api-docs:
        path: /api-docs              # API 문서 JSON 경로