server:
  port: 80

discodeit:
  jwt:
    cookie-secure: true
    registry: redis

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: info

management:
  endpoint:
    health:
      show-details: never
  health:
    redis:
      enabled: true
  info:
    env:
      enabled: false