server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL;INIT=CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE"
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

logging:
  level:

    com.sprint.misson.discodeit: DEBUG
    org.hibernate: WARN
