spring:
  application:
    name: discodeit

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false

  sql:
    init:
      mode: always

  boot:
    admin:
      client:
        instance:
          name: discodeit

discodeit:
  storage:
    type: local
    local:
      root-path: data/binaryContents

logging:
  level:
    root: INFO
    com.sprint.mission.discodeit: INFO
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  application:
    name: Discodeit
    version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}
