server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://[운영_DB_IP]:5432/discodeit_prod
    # [보안 중요] 아이디와 비밀번호는 파일에 직접 적지 않음
    # 서버의 환경변수(Environment Variables)에서 값을 읽어오도록 설정
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}

logging:
  level:
    org.hibernate.SQL: warn
    com.sprint.mission.discodeit: info

# 운영 환경 고민 좀 더 해보기
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
